### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by fallin911** [greenMikeEU/SmartMeterEVNKaifaMA309#1]
Hallo!
Könntest du bitte das Dashboard, welches bei deinem Tutorial zu sehen ist, von Grafana veröffentlichen?

**Comment by greenMikeEU** [comment]
Hallo, 
kann man das Exportieren ?
Ich muss mal einen Beitrag dazu schreiben.

**Comment by greenMikeEU** [comment]
Danke für die Info.
Ich schreibe gerade einen Blogbeitrag und zeige die Einstellungen her ich werde auch die Settings verlinken bzw zum Download bereitstellen. Kann noch ein paar Tage dauern

**Comment by greenMikeEU** [comment]
Hallo,
ich habe alle nötigen Infos auf meine Website gestellt wenn noch Fragen sind einfach melden.
LG Michael

**Comment by greenMikeEU** [comment]
https://www.michaelreitbauer.at/smart-meter-dashboard-in-grafana-influxdb/
