### ISSUE TITLE
Geht leider nicht mehr

### ISSUE THREAD

**Issue by tonka3000** [greenMikeEU/SmartMeterEVNKaifaMA309#16]
Hallo @greenMikeEU ,

danke für das tolle Skript. Hat bis gestern perfekt funktioniert. Seit gestern (08.04.2023) 15:00 bekomm ich plöztlich ein anderes xml zurück, wo keine `uint32` or `uint16` vorkommen.

Geht das bei dir/euch noch oder habt ihr das gleich Problem bzw. eine Idee was man machen kann?

Vielen Dank
Michael

**Comment by hansratzinger** [comment]
Hast du irgend ein Update gemacht? Ich habe seit 9 Monaten nun alles unter Docker laufen und damit alles gekapselt. Wenn das einmal funktioniert läuft das dann ungestört vom übrigen Betriebssystem. Es ist wesentlich einfacher als es sich anhört. Ich habe Anleitung dazu hier veröffentlicht: (https://hansratzinger.github.io/smartmeter-docker/)

**Comment by greenMikeEU** [comment]
Hallo @tonka3000,

welchen Pharser hast du verwendet ? html5lib oder lxml?
` soup = BeautifulSoup(xml, 'lxml')`
` soup = BeautifulSoup(xml, 'hmtl5lib')`
ich habe den html5lib auf den lxml geändert und dann hat es wieder funktioniert 
musst noch die Bibliothek installieren mir pip install lxml

**Comment by tonka3000** [comment]
Hey @greenMikeEU ,

Ich habe BeautifulSoup mit `BeautifulSoup(xml, "html.parser" )` laufen. Mit lxml gings bei mir nicht trotz library installieren.
Das komische ist das der xml content gar nicht mehr enthält die Daten die im Script abgefragt werden enthält.

Ein `print(xml)` vorm `BeautifulSoup(xml, "html.parser" )`  schaut wie folgt aus

```
<WiredMBus len="FE" >
<TargetAddress Value="67" />
<SourceAddress Value="1" />
</WiredMBus>
<WiredMBus len="18" >
<TargetAddress Value="67" />
<SourceAddress Value="1" />
<!--
IDIS system title:
Manufacturer Code: KFM
Function type: Disconnector extension, Multi Utility extension
-->
  <GeneralGloCiphering>
    <SystemTitle Value="BBB64D65509A539B" />
    <CipheredService Value="200000...E84DFD42BB68D57...C3AC80" />
  </GeneralGloCiphering>

</WiredMBus>
```

Inhalte wie CipheredService  Value hab ich gekürzt und mit `...` ersetzt.

Wenn ich mich richtig erinnere sollte der Inhalt anderes aussehen. Es sie für mich so aus als wäre der content jetzt im CipheredService Value.

@hansratzinger Hab nichts verändert.

**Comment by greenMikeEU** [comment]
Hallo,
hast du einen Test Datensatz für mich und dein Pin?
Hier kannst du es testen Daten einfach in Zeile 90 einfügen und den Key in Zeile 43
[AusleseSkript.zip](https://github.com/greenMikeEU/SmartMeterEVNKaifaMA309/files/11184204/AusleseSkript.zip)

**Comment by tonka3000** [comment]
Ist der Datensatz von der Stelle korrekt `daten = ser.read(size=282).hex()`?

**Comment by greenMikeEU** [comment]
Hallo am besten du schickst mir deine Daten und den Key und ich versuche es nochmal 
ich weiß nicht genau was du meinst.

Es gibt aber noch einen anderen Weg die Daten rauszusuchen aber dieser ist mühselig und werde ich erst machen wenn es keine Alternative mehr gibt

**Comment by tonka3000** [comment]
Ich schick dir Daten per mail

**Comment by tonka3000** [comment]
@greenMikeEU Ich hab es jetzt wieder zum Laufen gebracht. Ich habe nochmal den Key angefragt und der war anders 🤪.
Mit dem neuen Key geht es wieder ohne Probleme. D.h. wenn die Daten ohne den `uint32` und `uint16` bekommt hat die Entschlüsselung nicht funktioniert.
