### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml

### ISSUE THREAD

**Issue by NullP01n7er** [greenMikeEU/SmartMeterEVNKaifaMA309#7]
Hallo,

vielen Dank für dein Skript!
Anfangs hatte ich die Exception "bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml"
Wenn ich in der Zeile 65 den Parser von 'lxml' auf 'html.parser' ändere, funktioniert es bei mir.

lg
Michael

**Comment by juliank2008** [comment]
Ich hab dafür eine Pull-Request eröffnet:
https://github.com/greenMikeEU/SmartMeterEVNKaifaMA309/pull/13

**Comment by greenMikeEU** [comment]
Hallo,
eine neue Version befindet sich gerade in der Beta mit der html5lib. Sobald sich diese Bewährt hat wird sie hier hochgeladen
